[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    tzapu/WiFiManager @ ^2.0.16-rc.2
    knolleary/PubSubClient @ ^2.8
    4-20ma/ModbusMaster @ ^2.0.1
